#!/usr/bin/env python3
"""Regenerate the static per-template circuit-count table for the docs.

The overview page shows how many circuits each topology template enumerates.
Computing those counts at documentation-build time (the retired
``topology-counts`` Sphinx directive) meant fully enumerating every template on
every build -- several minutes, dominated by the two 3-stage fully-differential
templates at ~23k circuits each.  Instead we snapshot the counts into a static
reStructuredText table, checked into the repo and ``.. include::``-ed by
``docs/overview.rst``, so the build stays fast.

Run this whenever the enumeration changes (a new variant, a compatibility
filter, a template) to refresh the snapshot::

    python tools/gen_topology_counts.py

It rewrites ``docs/topology_counts.rst`` in place; commit the result.
"""
from pathlib import Path

from circuitgenome.synthesizer import enumerate_circuits
from circuitgenome.synthesizer.loader import load_modules, load_topologies

OUTPUT = Path(__file__).resolve().parent.parent / "docs" / "topology_counts.rst"


def _count_per_template():
    """Return ``[(template_name, circuit_count), ...]`` under the default
    enumeration config (``unsupported`` / ``bias_infeasible`` variants excluded).
    """
    modules = load_modules()
    rows = [
        (t.name, sum(1 for _ in enumerate_circuits(t, modules)))
        for t in load_topologies()
    ]
    # Group the rows by stage count (one_* , two_* , three_*) so all two-stage
    # templates sit together and all three-stage templates sit together; a
    # stable sort keeps the original relative order within each group.
    stage_rank = {"one": 1, "two": 2, "three": 3}
    rows.sort(key=lambda r: stage_rank.get(r[0].split("_")[0], 99))
    return rows


def _render(rows):
    total = sum(n for _, n in rows)
    lines = [
        ".. DO NOT EDIT -- generated by tools/gen_topology_counts.py.",
        ".. Regenerate with `python tools/gen_topology_counts.py` when the",
        ".. enumeration (variants, compatibility filters, templates) changes.",
        "",
        ".. list-table::",
        "   :header-rows: 1",
        "   :widths: 70 30",
        "",
        "   * - Template name",
        "     - Circuits generated",
    ]
    for name, n in rows:
        lines.append(f"   * - ``{name}``")
        lines.append(f"     - {n:,}")
    lines.append("   * - **Total**")
    lines.append(f"     - **{total:,}**")
    return "\n".join(lines) + "\n"


def main():
    rows = _count_per_template()
    OUTPUT.write_text(_render(rows))
    print(f"wrote {OUTPUT} ({len(rows)} templates, {sum(n for _, n in rows):,} total)")


if __name__ == "__main__":
    main()
